-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 17:51:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StudentsPerformance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StudentsPerformance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StudentsPerformance` DEFAULT CHARACTER SET utf8 ;
USE `StudentsPerformance` ;

-- -----------------------------------------------------
-- Table `StudentsPerformance`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`students` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `middlename` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`id_student`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`exams` (
  `id_exam` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `room_number` INT NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `teacher_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_exam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`grades` (
  `id_grade` INT NOT NULL AUTO_INCREMENT,
  `grade` INT NOT NULL,
  `id_student` INT NOT NULL,
  `id_exam` INT NOT NULL,
  PRIMARY KEY (`id_grade`),
  INDEX `student_idx` (`id_student` ASC) VISIBLE,
  INDEX `exam_idx` (`id_exam` ASC) VISIBLE,
  CONSTRAINT `student`
    FOREIGN KEY (`id_student`)
    REFERENCES `StudentsPerformance`.`students` (`id_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `exam`
    FOREIGN KEY (`id_exam`)
    REFERENCES `StudentsPerformance`.`exams` (`id_exam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
