-- MySQL Script generated by MySQL Workbench
-- Sun Mar 12 14:36:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StudentsPerformance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StudentsPerformance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StudentsPerformance` DEFAULT CHARACTER SET utf8 ;
USE `StudentsPerformance` ;

-- -----------------------------------------------------
-- Table `StudentsPerformance`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`groups` (
  `id_group` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`students` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `middlename` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `id_group` INT NOT NULL,
  PRIMARY KEY (`id_student`),
  INDEX `groups_idx` (`id_group` ASC) VISIBLE,
  CONSTRAINT `groups`
    FOREIGN KEY (`id_group`)
    REFERENCES `StudentsPerformance`.`groups` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`teachers` (
  `id_teacher` INT NOT NULL AUTO_INCREMENT,
  `teacher_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_teacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`subjects` (
  `id_subject` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_subject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`exams` (
  `id_exam` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `room_number` INT NOT NULL,
  `id_subject` INT NOT NULL,
  `id_teacher` INT NOT NULL,
  PRIMARY KEY (`id_exam`),
  INDEX `teachers_idx` (`id_teacher` ASC) VISIBLE,
  INDEX `subjects_idx` (`id_subject` ASC) VISIBLE,
  CONSTRAINT `teachers`
    FOREIGN KEY (`id_teacher`)
    REFERENCES `StudentsPerformance`.`teachers` (`id_teacher`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `StudentsPerformance`.`subjects` (`id_subject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StudentsPerformance`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudentsPerformance`.`grades` (
  `id_grade` INT NOT NULL AUTO_INCREMENT,
  `grade` INT NOT NULL,
  `id_student` INT NOT NULL,
  `id_exam` INT NOT NULL,
  PRIMARY KEY (`id_grade`),
  INDEX `students_idx` (`id_student` ASC) VISIBLE,
  INDEX `exams_idx` (`id_exam` ASC) VISIBLE,
  CONSTRAINT `students`
    FOREIGN KEY (`id_student`)
    REFERENCES `StudentsPerformance`.`students` (`id_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `exams`
    FOREIGN KEY (`id_exam`)
    REFERENCES `StudentsPerformance`.`exams` (`id_exam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
